---
abstract: 'RedisDB based cache system'
author:
  - 'binary.com <rakesh@binary.com>'
build_requires:
  DateTime: '0'
  JSON: '0'
  Test::FailWarnings: '0'
  Test::More: '0'
  Test::Most: '0.22'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.141520'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Cache-RedisDB
no_index:
  directory:
    - t
    - inc
requires:
  RedisDB: '2.14'
  Sereal: '0'
  perl: '5.01'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Cache-RedisDB
  homepage: https://github.com/binary-com/perl-Cache-RedisDB
version: '0.02'
