---
abstract: 'RedisDB based cache system'
author:
  - 'binary.com <rakesh@binary.com>'
build_requires:
  DateTime: '0'
  Digest::SHA: '0'
  JSON: '0'
  Test::Differences: '0.61'
  Test::FailWarnings: '0'
  Test::More: '0.96'
  Test::Most: '0.22'
  Test::TCP: '1.17'
configure_requires:
  ExtUtils::MakeMaker: '6.3002'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.141520'
keywords:
  - cache
  - redisdb
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Cache-RedisDB
no_index:
  directory:
    - t
    - inc
requires:
  RedisDB: '2.14'
  Sereal: '0'
  perl: '5.008004'
resources:
  bugtracker: https://github.com/binary-com/perl-Cache-RedisDB/issues
  homepage: https://github.com/binary-com/perl-Cache-RedisDB
  license: http://dev.perl.org/licenses/
version: '0.04'
x_contributors:
  - 'Rakesh Kumar Shardiwal <shardiwal@cpan.org>'
